- hosts: labs
  tasks: 
    - name: install pyhton-docker
      yum:
        #name: python-docker
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python-pip
        - python-docker
      pip: 
        name: docker-py
      pip: 
        name: docker-compose
      when:
        - ansible_distribution == "CentOS"
    - name: install python-docker
      apt: 
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python-pip
        - python-docker
      pip: 
        name: docker-py
      pip: 
        name: docker-compose
      when:
        - ansible_distribution == "Ubuntu"
    - name: run container
      docker_container:
        name: apache2
        state: started
        image: sultonyakbar/httpd:6
        published_ports:
          - 80:80
          
